from __future__ import annotations

import json
import os
import re
from dataclasses import asdict, dataclass
from typing import Any
from urllib.error import HTTPError, URLError
from urllib.parse import urlparse
from urllib.request import Request, urlopen

from .models import Finding, ReviewReport

GITHUB_API_URL = "https://api.github.com"
DEFAULT_PR_COMMENT_MARKER = "<!-- repo-review-agent:pr-comment -->"


class GitHubIntegrationError(RuntimeError):
    pass


@dataclass(frozen=True)
class IssueDraft:
    title: str
    body: str
    labels: list[str]

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


def parse_github_repo(value: str) -> str | None:
    if re.fullmatch(r"[\w.-]+/[\w.-]+", value):
        return value.removesuffix(".git")

    parsed = urlparse(value)
    if parsed.netloc.lower() not in {"github.com", "www.github.com"}:
        return None

    parts = [part for part in parsed.path.split("/") if part]
    if len(parts) < 2:
        return None

    owner = parts[0]
    repo = parts[1].removesuffix(".git")
    if not owner or not repo:
        return None
    return f"{owner}/{repo}"


def issue_drafts_from_report(report: ReviewReport) -> list[IssueDraft]:
    drafts: list[IssueDraft] = []
    for finding in report.findings:
        if finding.severity == "info":
            continue
        drafts.append(issue_draft_from_finding(finding))
    return drafts


def issue_draft_from_finding(finding: Finding) -> IssueDraft:
    evidence = "\n".join(f"- {item}" for item in finding.evidence)
    evidence_paths = "\n".join(f"- `{path}`" for path in finding.evidence_paths)
    body = (
        "Generated by GitHub Repo Review Agent.\n\n"
        f"## Severity\n\n`{finding.severity}`\n\n"
        f"## Category\n\n`{finding.category}`\n\n"
        "## Evidence\n\n"
        f"{evidence or '- No evidence listed.'}\n\n"
        "## Evidence Files\n\n"
        f"{evidence_paths or '- No evidence files listed.'}\n\n"
        "## Recommendation\n\n"
        f"{finding.recommendation}\n"
    )
    return IssueDraft(
        title=f"[{finding.severity.upper()}] {finding.title}",
        body=body,
        labels=[],
    )


def build_pr_comment_body(report: ReviewReport) -> str:
    lines = [
        "## Repository Review Agent",
        "",
        "### Summary",
        "",
    ]
    lines.extend(f"- {item}" for item in report.overview)

    if report.ai_review and report.ai_review.status == "generated":
        lines.extend(["", "### AI Review", "", report.ai_review.summary])

    lines.extend(["", "### Findings", ""])
    actionable = [finding for finding in report.findings if finding.severity != "info"]
    if not actionable:
        lines.append("- No immediate issue suggestions.")
    else:
        for finding in actionable:
            evidence_paths = ", ".join(f"`{path}`" for path in finding.evidence_paths)
            file_context = f" Files: {evidence_paths}." if evidence_paths else ""
            lines.append(
                f"- **{finding.severity.upper()}**: {finding.title} - "
                f"{finding.recommendation}{file_context}"
            )

    return "\n".join(lines).strip() + "\n"


class GitHubClient:
    def __init__(
        self,
        *,
        token: str | None = None,
        api_url: str = GITHUB_API_URL,
        timeout: float = 30,
    ) -> None:
        self.token = token or os.environ.get("GITHUB_TOKEN")
        self.api_url = api_url.rstrip("/")
        self.timeout = timeout

    def require_token(self) -> str:
        if not self.token:
            raise GitHubIntegrationError("GITHUB_TOKEN is required for GitHub create mode.")
        return self.token

    def create_issue(self, repo: str, draft: IssueDraft) -> dict[str, Any]:
        payload: dict[str, Any] = {
            "title": draft.title,
            "body": draft.body,
        }
        if draft.labels:
            payload["labels"] = draft.labels
        return self._request_dict("POST", f"/repos/{repo}/issues", payload)

    def create_issue_comment(self, repo: str, issue_number: int, body: str) -> dict[str, Any]:
        return self._request_dict(
            "POST",
            f"/repos/{repo}/issues/{issue_number}/comments",
            {"body": body},
        )

    def list_issue_comments(self, repo: str, issue_number: int) -> list[dict[str, Any]]:
        comments = self._request_list(
            "GET",
            f"/repos/{repo}/issues/{issue_number}/comments?per_page=100",
        )
        return [comment for comment in comments if isinstance(comment, dict)]

    def update_issue_comment(self, repo: str, comment_id: int, body: str) -> dict[str, Any]:
        return self._request_dict(
            "PATCH",
            f"/repos/{repo}/issues/comments/{comment_id}",
            {"body": body},
        )

    def upsert_issue_comment(
        self,
        repo: str,
        issue_number: int,
        body: str,
        *,
        marker: str,
    ) -> tuple[str, dict[str, Any]]:
        marked_body = ensure_comment_marker(body, marker)
        existing_comment = self.find_issue_comment(repo, issue_number, marker)
        if existing_comment is not None:
            comment_id = existing_comment.get("id")
            if isinstance(comment_id, int):
                return "updated", self.update_issue_comment(repo, comment_id, marked_body)
        return "created", self.create_issue_comment(repo, issue_number, marked_body)

    def find_issue_comment(
        self,
        repo: str,
        issue_number: int,
        marker: str,
    ) -> dict[str, Any] | None:
        for comment in self.list_issue_comments(repo, issue_number):
            if marker in str(comment.get("body", "")):
                return comment
        return None

    def _request_json(
        self,
        method: str,
        path: str,
        payload: dict[str, Any] | None = None,
    ) -> Any:
        token = self.require_token()
        data = None if payload is None else json.dumps(payload).encode("utf-8")
        request = Request(
            f"{self.api_url}{path}",
            data=data,
            headers={
                "Accept": "application/vnd.github+json",
                "Authorization": f"Bearer {token}",
                "Content-Type": "application/json",
                "User-Agent": "github-repo-review-agent",
                "X-GitHub-Api-Version": "2022-11-28",
            },
            method=method,
        )
        try:
            with urlopen(request, timeout=self.timeout) as response:
                body = response.read().decode("utf-8")
        except HTTPError as exc:
            body = exc.read().decode("utf-8", errors="replace")
            raise GitHubIntegrationError(f"GitHub API returned HTTP {exc.code}: {body}") from exc
        except URLError as exc:
            raise GitHubIntegrationError(f"Could not connect to GitHub API: {exc.reason}") from exc

        try:
            data = json.loads(body)
        except json.JSONDecodeError as exc:
            raise GitHubIntegrationError(f"GitHub API returned invalid JSON: {body[:500]}") from exc

        return data

    def _request_dict(
        self,
        method: str,
        path: str,
        payload: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        data = self._request_json(method, path, payload)
        if not isinstance(data, dict):
            raise GitHubIntegrationError("GitHub API returned an unexpected response.")
        return data

    def _request_list(
        self,
        method: str,
        path: str,
        payload: dict[str, Any] | None = None,
    ) -> list[Any]:
        data = self._request_json(method, path, payload)
        if not isinstance(data, list):
            raise GitHubIntegrationError("GitHub API returned an unexpected response.")
        return data


def apply_github_issue_mode(
    *,
    report: ReviewReport,
    repo: str,
    mode: str,
    token: str | None = None,
) -> list[dict[str, Any]]:
    drafts = issue_drafts_from_report(report)
    if mode == "dry-run":
        return [{"mode": "dry-run", "repo": repo, **draft.to_dict()} for draft in drafts]
    if mode == "create":
        client = GitHubClient(token=token)
        created: list[dict[str, Any]] = []
        for draft in drafts:
            response = client.create_issue(repo, draft)
            created.append(
                {
                    "mode": "create",
                    "repo": repo,
                    "title": draft.title,
                    "html_url": response.get("html_url"),
                    "number": response.get("number"),
                }
            )
        return created
    return []


def apply_github_pr_comment_mode(
    *,
    report: ReviewReport,
    repo: str,
    pr_number: int,
    mode: str,
    token: str | None = None,
) -> dict[str, Any]:
    body = ensure_comment_marker(build_pr_comment_body(report), DEFAULT_PR_COMMENT_MARKER)
    if mode == "dry-run":
        return {"mode": "dry-run", "repo": repo, "pr_number": pr_number, "body": body}
    if mode == "create":
        client = GitHubClient(token=token)
        response = client.create_issue_comment(repo, pr_number, body)
        return {
            "mode": "create",
            "repo": repo,
            "pr_number": pr_number,
            "html_url": response.get("html_url"),
        }
    if mode == "upsert":
        client = GitHubClient(token=token)
        action, response = client.upsert_issue_comment(
            repo,
            pr_number,
            body,
            marker=DEFAULT_PR_COMMENT_MARKER,
        )
        return {
            "mode": "upsert",
            "action": action,
            "repo": repo,
            "pr_number": pr_number,
            "html_url": response.get("html_url"),
        }
    return {}


def ensure_comment_marker(body: str, marker: str) -> str:
    if marker in body:
        return body
    return f"{marker}\n{body}"
