export const reportCopy = {
  en: {
    generatedReport: "Generated Report",
    repositoryReview: "Repository Review",
    generated: "Generated",
    noPriorityRisks: "No priority risks",
    priority: "priority",
    aiNotSelected: "not selected",
    executiveSummary: "Executive Summary",
    metrics: "Metrics",
    frameworkSignals: "Framework Signals",
    noFrameworkSignals: "No framework signals were detected.",
    aiReview: "AI Review",
    aiReviewError: "AI review was not generated",
    findings: "Findings",
    agentTrace: "Agent Trace",
    noTrace: "No agent trace was recorded for this run.",
    step: "Step",
    provider: "Provider",
    model: "Model",
    status: "Status",
    evidence: "Evidence",
    evidencePaths: "Evidence files",
    recommendation: "Recommendation",
    issueBacklog: "GitHub Issue Backlog",
    noIssues: "No immediate issue suggestions.",
    copy: "Copy",
    download: "Download",
    close: "Close",
    metricLabels: {
      files_scanned: "Files scanned",
      files_skipped: "Files skipped",
      source_files: "Source files",
      test_files: "Test files",
      dependency_files: "Dependencies",
      ci_files: "CI files"
    },
    severity: {
      critical: "Critical",
      high: "High",
      medium: "Medium",
      low: "Low",
      info: "Info"
    }
  },
  "zh-CN": {
    generatedReport: "生成的报告",
    repositoryReview: "仓库评审",
    generated: "生成时间",
    noPriorityRisks: "暂无重点风险",
    priority: "重点风险",
    aiNotSelected: "未选择",
    executiveSummary: "执行摘要",
    metrics: "指标",
    frameworkSignals: "框架信号",
    noFrameworkSignals: "未检测到框架信号。",
    aiReview: "AI 评审",
    aiReviewError: "AI 评审未生成",
    findings: "发现",
    agentTrace: "Agent 执行轨迹",
    noTrace: "本次运行没有记录 Agent 执行轨迹。",
    step: "步骤",
    provider: "提供方",
    model: "模型",
    status: "状态",
    evidence: "证据",
    evidencePaths: "证据文件",
    recommendation: "建议",
    issueBacklog: "GitHub Issue 待办",
    noIssues: "暂无需要立即创建的 Issue 建议。",
    copy: "复制",
    download: "下载",
    close: "关闭",
    metricLabels: {
      files_scanned: "扫描文件数",
      files_skipped: "跳过文件数",
      source_files: "源码文件数",
      test_files: "测试文件数",
      dependency_files: "依赖清单数",
      ci_files: "CI 文件数"
    },
    severity: {
      critical: "严重",
      high: "高",
      medium: "中",
      low: "低",
      info: "信息"
    }
  }
};
